<?php

use App\Http\Middleware\ApiAuthentication;
//use DB;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class FreelancerTest extends TestCase
{

//    use RefreshDatabase;

//    public function setUp()
//    {
//        parent::setUp(); // TODO: Change the autogenerated stub
//
////        $this->refreshDatabase();
//    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function testAuthontification() {

        $response = $this->get('/');

        $response->assertStatus(401);
    }

    public function testAuthontificationFreelancers() {

        $response = $this->get('/api/v1/freelancers');

        $response->assertStatus(401);
    }

    public function testGetFreelancees() {

        $response = $this->get('/api/v1/freelancers', self::getToken());

        $response->assertStatus(200);

    }

    public function testCreateFreelancer() {

        $data = [];

        $response = $this->post('/api/v1/freelancers', $data, self::getToken());

        $response->assertStatus(422);

        $data = [
            'name' => 'Buka',
            'price' => 300,
            'email' => 'test@asd.ru',
            'phone' => '88005553535',
        ];

        $response = $this->post('/api/v1/freelancers', $data, self::getToken());


        $response->assertStatus(201);

    }

    private static function getToken() {

        return [ApiAuthentication::API_KEY_HEADER => config('services.api.token')];
    }

}
